version: "3"
services:
  express:
    build: .
    image: diginode:latest
    container_name: diginode
    ports:
      - 9000:9000
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped